manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: zephyr-v3.0.0
      clone-depth: 1
      import:
        name-allowlist:
          - hal_espressif
          - hal_nordic
          - cmsis
  self:
    west-commands: scripts/west-commands.yml